version: 0.2
phases:
   install:
     runtime-versions:
        dotnet: 3.0
       
   pre_build:
     commands:
       - echo Enter into pre_build phases...
       - echo Nothing to do in this phase
   build:
     commands:
       - aws --version
       - echo building sample api microservices..
       - cd SampleAPIApplication/SampleAPIApplication
       - echo Logging in to Amazon ECR...
       - $(aws ecr get-login --region eu-central-1 --no-include-email --registry-ids $EcrRepoAccount)
       - REPOSITORY_URI=$EcrRepoAccount.dkr.ecr.eu-central-1.amazonaws.com/SampleAPIApplication
       - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
       - IMAGE_TAG=${COMMIT_HASH:=latest}
       - echo Build started on `date`
       - echo Building the Docker image...
       - docker build -t $REPOSITORY_URI:latest .
       - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
       - echo Build completed on `date`
       - echo Pushing the Docker images...
       - docker push $REPOSITORY_URI:latest
       - docker push $REPOSITORY_URI:$IMAGE_TAG
       - cd ../..
       - echo Writing image definitions file...
       - printf '[{"name":"SampleAPIApplication","imageUri":"%s"}],' $REPOSITORY_URI:$IMAGE_TAG > SampleAPIApplication.json
   post_build:
     commands:
       - echo post_build completed...
artifacts:
    files: 
      - SampleAPIApplication.json